[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "CaskaydiaCove NF"

[scrolling]
history = 5000

[window]
dynamic_padding = true
opacity = 0.98
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
